# Title: pySCENIC run + AUCell integration + visualization (Python)
# Project: AD snRNA-seq multi-model analysis
# Author: Jung Hyun Park
# Purpose: Build a pySCENIC-compatible loom file from exported counts/metadata,
#          then integrate AUCell outputs and visualize regulon activity embeddings.
# Notes:
#   - Assumes upstream preprocessing/annotation was done in R/Seurat.
#   - This script does NOT run GRN/ctx/AUCell itself; those are typically run via CLI/SLURM.
#   - Supports either MTX (recommended) or CSV counts export.

import os
import numpy as np
import pandas as pd
import scanpy as sc
import loompy as lp

# Optional (UMAP/tSNE on AUCell)
import umap
from MulticoreTSNE import MulticoreTSNE as TSNE

np.random.seed(42)

# -----------------------
# Parameters (edit here)
# -----------------------
wdir = "outputs/pyscenic"
os.makedirs(wdir, exist_ok=True)
os.chdir(wdir)

# Input (choose ONE counts source)
USE_MTX = True  # recommended
mtx_dir = "./raw_counts_mtx"                 # contains matrix.mtx, genes.tsv, barcodes.tsv
counts_csv = "./raw_counts_mat.csv"          # only if USE_MTX=False

meta_csv = "./meta.csv"

# Optional embedding export from R (e.g. Harmony UMAP)
embedding_csv = "./umap_coord.csv"           # set to None to skip
embedding_key = "X_umap_harmony"             # name inside adata.obsm

# Outputs
loom_for_scenic = "./filtered_scenic_input.loom"
anndata_path = "./anndata_for_scenic.h5ad"

# pySCENIC AUCell output loom (generated by CLI step)
pyscenic_output_loom = "./pyscenic_output.loom"  # contains ca.RegulonsAUC, ca.CellID
# Integrated outputs
scenic_umap_out = "./scenic_auc_umap.tsv"
scenic_tsne_out = "./scenic_auc_tsne.tsv"

# Scanpy plotting
sc.settings.verbosity = 2
sc.set_figure_params(dpi=150, fontsize=10, dpi_save=300)

# -----------------------
# Load counts into AnnData
# -----------------------
if USE_MTX:
  # Expect genes.tsv and barcodes.tsv written by 10a
  genes = pd.read_csv(os.path.join(mtx_dir, "genes.tsv"), header=None)[0].tolist()
  barcodes = pd.read_csv(os.path.join(mtx_dir, "barcodes.tsv"), header=None)[0].tolist()

  # Read MTX into sparse matrix (genes x cells) then transpose to cells x genes for AnnData
  from scipy.io import mmread
  X = mmread(os.path.join(mtx_dir, "matrix.mtx")).tocsr()
  X = X.transpose().tocsr()  # cells x genes

  adata = sc.AnnData(X=X)
  adata.obs_names = barcodes
  adata.var_names = genes
else:
  # CSV exported as genes x cells -> transpose to cells x genes
  adata = sc.read_csv(counts_csv).T

print(adata)

# -----------------------
# Load metadata
# -----------------------
meta = pd.read_csv(meta_csv, index_col=0)
# Align to adata
meta = meta.reindex(adata.obs_names)
if meta.isnull().all(axis=1).any():
  raise ValueError("Some cells in counts were not found in metadata rownames.")

adata.obs = meta

# -----------------------
# Add optional embedding (from R)
# -----------------------
if embedding_csv is not None and os.path.exists(embedding_csv):
  emb = pd.read_csv(embedding_csv, index_col=0)
  emb = emb.reindex(adata.obs_names)
  if emb.isnull().any().any():
    # If some missing, fill with 0 (or raise)
    emb = emb.fillna(0.0)
  adata.obsm[embedding_key] = emb.values
  print(f"Added embedding to adata.obsm['{embedding_key}'] with shape {emb.shape}")

# Save AnnData snapshot
adata.write(anndata_path)
print(f"Wrote AnnData: {anndata_path}")

# -----------------------
# Create loom file for pySCENIC (genes x cells required)
# -----------------------
# pySCENIC expects loom matrix as genes x cells
row_attrs = {"Gene": np.array(adata.var_names)}

# Minimal useful col attrs (add more if you want)
col_attrs = {
  "CellID": np.array(adata.obs_names),
  "nGene": np.array((adata.X > 0).sum(axis=1)).flatten(),
  "nUMI": np.array(adata.X.sum(axis=1)).flatten(),
}

# Add ALL metadata columns as loom column attributes
for col in adata.obs.columns:
  # Ensure numpy arrays (and keep them JSON/loom friendly)
  col_attrs[col] = np.array(adata.obs[col].values)

# Write loom
lp.create(loom_for_scenic, adata.X.transpose(), row_attrs, col_attrs)
print(f"Wrote loom for pySCENIC: {loom_for_scenic}")

# -----------------------
# Run 10c slurm job first and then integrate the AUCell output
# -----------------------
if os.path.exists(pyscenic_output_loom):
  lf = lp.connect(pyscenic_output_loom, mode="r", validate=False)

  # AUCell matrix: cells x regulons
  auc_mtx = pd.DataFrame(lf.ca.RegulonsAUC, index=lf.ca.CellID)
  lf.close()

  print("AUCell matrix:", auc_mtx.shape)

  # Align AUCell to current AnnData cell order
  auc_mtx = auc_mtx.reindex(adata.obs_names)
  if auc_mtx.isnull().any().any():
    # If some cells missing, fill with 0 (or raise). Usually indicates mismatch in barcodes.
    auc_mtx = auc_mtx.fillna(0.0)

  # Store AUCell in AnnData (obsm is typical)
  adata.obsm["X_scenic_auc"] = auc_mtx.values
  adata.uns["scenic_regulons"] = list(auc_mtx.columns)

  # Compute UMAP/tSNE on AUCell space
  run_umap = umap.UMAP(
    n_neighbors=20, min_dist=0.4, metric="correlation", random_state=42
  ).fit_transform
  scenic_umap = run_umap(auc_mtx.values)
  pd.DataFrame(scenic_umap, columns=["X", "Y"], index=auc_mtx.index).to_csv(
    scenic_umap_out, sep="\t"
  )
  adata.obsm["SCENIC_AUC_UMAP"] = scenic_umap

  tsne = TSNE(perplexity=50, n_iter=1500, n_jobs=20, random_state=42)
  scenic_tsne = tsne.fit_transform(auc_mtx.values)
  pd.DataFrame(scenic_tsne, columns=["X", "Y"], index=auc_mtx.index).to_csv(
    scenic_tsne_out, sep="\t"
  )
  adata.obsm["SCENIC_AUC_tSNE"] = scenic_tsne

  # Example plots (edit colors to your available obs columns)
  # These will save into ./figures by default
  for basis, suffix in [("SCENIC_AUC_UMAP", "_scenic_auc_umap"), ("SCENIC_AUC_tSNE", "_scenic_auc_tsne")]:
    if basis in adata.obsm:
      sc.pl.embedding(
        adata,
        basis=basis,
        color=[c for c in ["cell_type", "cluster_label", "Condition"] if c in adata.obs.columns],
        ncols=2,
        use_raw=False,
        save=f"{suffix}.pdf",
      )

  # Save integrated AnnData
  adata.write(anndata_path)
  print(f"Updated AnnData with AUCell embeddings: {anndata_path}")
else:
  print(f"AUCell output loom not found: {pyscenic_output_loom} (skipping integration)")

print("Done.")
