"""
Utility functions for loading and processing pySCENIC outputs.

Author: Jung Hyun Park
"""

import pandas as pd
from pathlib import Path


def load_auc_matrix(auc_path):
    """
    Load AUCell matrix generated by pySCENIC.

    Parameters
    ----------
    auc_path : str or Path
        Path to AUCell output (.csv or .tsv)

    Returns
    -------
    pd.DataFrame
        Cells x regulons AUCell matrix
    """
    auc_path = Path(auc_path)

    if auc_path.suffix == ".csv":
        df = pd.read_csv(auc_path, index_col=0)
    elif auc_path.suffix in [".tsv", ".txt"]:
        df = pd.read_csv(auc_path, sep="\t", index_col=0)
    else:
        raise ValueError(f"Unsupported file type: {auc_path.suffix}")

    return df


def load_metadata(metadata_path):
    """
    Load cell-level metadata exported from R.

    Parameters
    ----------
    metadata_path : str or Path
        Path to metadata file

    Returns
    -------
    pd.DataFrame
        Metadata indexed by cell barcode
    """
    meta = pd.read_csv(metadata_path, index_col=0)
    return meta


def merge_auc_with_metadata(auc_df, metadata_df):
    """
    Merge AUCell matrix with metadata.

    Parameters
    ----------
    auc_df : pd.DataFrame
        AUCell matrix
    metadata_df : pd.DataFrame
        Cell metadata

    Returns
    -------
    pd.DataFrame
        Combined DataFrame
    """
    common_cells = auc_df.index.intersection(metadata_df.index)
    merged = pd.concat(
        [metadata_df.loc[common_cells], auc_df.loc[common_cells]],
        axis=1
    )
    return merged


def save_table(df, out_path):
    """
    Save DataFrame to disk.

    Parameters
    ----------
    df : pd.DataFrame
    out_path : str or Path
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path)

